
## Automatically generated by Xeda

project new {{design.name}}


# project set family {{settings.fpga.family}}
project set device {{settings.fpga.device}}
project set package {{settings.fpga.package}}
project set speed {{settings.fpga.speed}}
project set "Generate Detailed MAP Report" TRUE

{% for src in design.rtl.sources %}
xfile add -copy {{src.file}}
{%- endfor %}

project set top {{design.rtl.top}}

project set -process "Synthesize - XST" -opt_level "High"
project set -process "Synthesize - XST" -opt_mode "Speed" ## or Area



project set -process "Map" -logic_opt TRUE
project set -process "Map" -global_opt "Speed"  ## Off, Area, Power

project set "Place & Route Effort Level (Overall)" High

project set "Extra Effort (Highest PAR level only)" "Continue on Impossible"
project set "Report Type" "Verbose Report" -process "Generate Post-Place & Route Static Timing"


process run "Implement Design"

# project close

